/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          50:  '#f0f4ff',
          100: '#e0e9fe',
          200: '#c7d6fd',
          300: '#a5b8fb',
          400: '#8191f8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          950: '#1e1b4b',
        },
        surface: {
          50:  '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#020617',
        },
        accent: {
          cyan:   '#06b6d4',
          violet: '#8b5cf6',
          rose:   '#f43f5e',
          amber:  '#f59e0b',
          emerald:'#10b981',
        },
      },
      fontFamily: {
        sans:  ['Inter', 'system-ui', 'sans-serif'],
        mono:  ['"JetBrains Mono"', '"Fira Code"', 'monospace'],
        serif: ['"Lora"', 'Georgia', 'serif'],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '1rem' }],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
      },
      maxWidth: {
        '8xl': '88rem',
        'prose-lg': '75ch',
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body':         theme('colors.surface.700'),
            '--tw-prose-headings':     theme('colors.surface.900'),
            '--tw-prose-lead':         theme('colors.surface.600'),
            '--tw-prose-links':        theme('colors.brand.600'),
            '--tw-prose-bold':         theme('colors.surface.900'),
            '--tw-prose-counters':     theme('colors.surface.500'),
            '--tw-prose-bullets':      theme('colors.surface.400'),
            '--tw-prose-hr':           theme('colors.surface.200'),
            '--tw-prose-quotes':       theme('colors.surface.900'),
            '--tw-prose-quote-borders':theme('colors.brand.400'),
            '--tw-prose-captions':     theme('colors.surface.500'),
            '--tw-prose-code':         theme('colors.brand.700'),
            '--tw-prose-pre-code':     theme('colors.surface.200'),
            '--tw-prose-pre-bg':       theme('colors.surface.900'),
            '--tw-prose-th-borders':   theme('colors.surface.300'),
            '--tw-prose-td-borders':   theme('colors.surface.200'),
            maxWidth: 'none',
            a: {
              fontWeight: '500',
              textDecoration: 'underline',
              textDecorationColor: theme('colors.brand.300'),
              textUnderlineOffset: '3px',
              transition: 'color 0.15s, text-decoration-color 0.15s',
              '&:hover': {
                color: theme('colors.brand.700'),
                textDecorationColor: theme('colors.brand.500'),
              },
            },
            'h1,h2,h3,h4': { scrollMarginTop: '5rem' },
            pre: { borderRadius: '0.75rem', margin: '1.5rem 0' },
            code: {
              fontFamily: theme('fontFamily.mono').join(', '),
              fontSize: '0.875em',
              backgroundColor: theme('colors.surface.100'),
              padding: '0.125em 0.375em',
              borderRadius: '0.25rem',
              fontWeight: '400',
            },
            'code::before': { content: 'none' },
            'code::after':  { content: 'none' },
            blockquote: {
              borderLeftWidth: '4px',
              borderLeftColor: theme('colors.brand.400'),
              backgroundColor: theme('colors.brand.50'),
              borderRadius: '0 0.5rem 0.5rem 0',
              padding: '1rem 1.5rem',
              fontStyle: 'normal',
            },
          },
        },
        invert: {
          css: {
            '--tw-prose-body':          theme('colors.surface.300'),
            '--tw-prose-headings':      theme('colors.surface.50'),
            '--tw-prose-lead':          theme('colors.surface.400'),
            '--tw-prose-links':         theme('colors.brand.400'),
            '--tw-prose-bold':          theme('colors.surface.50'),
            '--tw-prose-counters':      theme('colors.surface.400'),
            '--tw-prose-bullets':       theme('colors.surface.600'),
            '--tw-prose-hr':            theme('colors.surface.700'),
            '--tw-prose-quotes':        theme('colors.surface.100'),
            '--tw-prose-quote-borders': theme('colors.brand.500'),
            '--tw-prose-captions':      theme('colors.surface.400'),
            '--tw-prose-code':          theme('colors.brand.300'),
            '--tw-prose-pre-code':      theme('colors.surface.200'),
            '--tw-prose-pre-bg':        theme('colors.surface.900'),
            '--tw-prose-th-borders':    theme('colors.surface.600'),
            '--tw-prose-td-borders':    theme('colors.surface.700'),
            a: {
              '&:hover': { color: theme('colors.brand.300') },
            },
            code: {
              backgroundColor: theme('colors.surface.800'),
            },
            blockquote: {
              backgroundColor: theme('colors.surface.800'),
              borderLeftColor: theme('colors.brand.500'),
            },
          },
        },
      }),
      animation: {
        'fade-in':       'fadeIn 0.5s ease-out',
        'slide-up':      'slideUp 0.4s ease-out',
        'slide-down':    'slideDown 0.3s ease-out',
        'pulse-slow':    'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'shimmer':       'shimmer 2s linear infinite',
        'progress-bar':  'progressBar 0.3s ease-out',
      },
      keyframes: {
        fadeIn:      { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp:     { from: { opacity: '0', transform: 'translateY(1rem)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideDown:   { from: { opacity: '0', transform: 'translateY(-0.5rem)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        shimmer:     { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        progressBar: { from: { width: '0%' }, to: { width: 'var(--progress)' } },
      },
      backgroundImage: {
        'gradient-radial':  'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':   'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'grid-pattern':     "url(\"data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%236366f1' fill-opacity='0.05'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E\")",
      },
      boxShadow: {
        'card':       '0 1px 3px 0 rgb(0 0 0 / 0.08), 0 1px 2px -1px rgb(0 0 0 / 0.08)',
        'card-hover': '0 10px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
        'glow':       '0 0 30px rgb(99 102 241 / 0.2)',
        'glow-lg':    '0 0 60px rgb(99 102 241 / 0.3)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};
